# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.srcs/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/video_out_pynq_z2_system_ila_1_0.xci
# IP: The module: 'video_out_pynq_z2_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/bd_c944.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c944 || ORIG_REF_NAME==bd_c944} -quiet] -quiet

# IP: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/bd_c944_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/bd_c944_ila_lib_0_ooc.xdc

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/bd_c944_ooc.xdc

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/video_out_pynq_z2_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.srcs/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/video_out_pynq_z2_system_ila_1_0.xci
# IP: The module: 'video_out_pynq_z2_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/bd_c944.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c944 || ORIG_REF_NAME==bd_c944} -quiet] -quiet

# IP: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/bd_c944_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c944_ila_lib_0 || ORIG_REF_NAME==bd_c944_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/ip/ip_0/bd_c944_ila_lib_0_ooc.xdc

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/bd_0/bd_c944_ooc.xdc

# XDC: c:/selected_hdmi_okok/pyzq/hw/hw_proj/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_system_ila_1_0/video_out_pynq_z2_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
